### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by dmpmuniz** [tibor-borsos-developments/hello-haylou#2]
Hi, sorry if this is a wrong place, is possible to port/adapt the firmware from miband4/any amazfit to haylou solar due to is similarity? Thanks you for you good work. (Sorry for my english)

**Comment by tibor-borsos-developments** [comment]
Hello!

I think it's impossible. They have other capabilities and use other hardware

**Comment by dmpmuniz** [comment]
Ok, thanks
