### ISSUE TITLE
watchface new feature doesn't work on Standalone mode of the app

### ISSUE THREAD

**Issue by kime01** [tibor-borsos-developments/hello-haylou#27]
Quite unstable for me applying the new feature of the app: changing the watchface (dial, as Haylou calls it) in Standalone mode. The most of the times it fails during uploading it. 
Plus: there's no support to add a custom watchface, like in the main app (the one everyone of us has abandoned for yours), right? Any project to add it in the future?
Thanks for your great work, Tibor.

**Comment by tibor-borsos-developments** [comment]
Hello!

Does the new 1.10.1 version work?

**Comment by kime01** [comment]
Hi Tibor, 
thanks for your reply: I am upgrading and I will test during today, I’ll let you know, 

thank you

regards

Alessio

Da: Tibor Borsos
Inviato: lunedì 1 febbraio 2021 09:15
A: tibor-borsos-developments/hello-haylou
Cc: kime01; Author
Oggetto: Re: [tibor-borsos-developments/hello-haylou] watchface new featuredoesn't work on Standalone mode of the app (#27)

Hello!
Does the new 1.10.1 version work?

**Comment by kime01** [comment]
hey Tibor. It's not a big problem, just to let you know, but in the latest version (1.10.3) you set again to high speed the upload transfer rate and (at least for my device, Solar) I had 2 upload successes out of 6 attempts. Maybe the previous speed was better (successa rate was actually 100%, time of transferring was more than 60-80 seconds). 
The "upload dial" window starts to count the percentage, then after 10-15 seconds, randomly, close itself removing the previous watchface resetting to the default one. thanks anyway,

**Comment by tibor-borsos-developments** [comment]
Hello!

Do you have any other Bluetooth devices connected to your phone (headphones, game controller, etc.)?
Try to disconnect them.

**Comment by kime01** [comment]
hey, 
Haylou Solar is the only device I have (always) connected with my phone. When I do the upload procedure they are less than 5cms far, I remove the band from my wrist. Success rate is confirmed but if it's just my personal issue it could be caused by the phone itself, maybe the MIUI or whatever. thanks

**Comment by kime01** [comment]
Hey Tibor, great idea giving the user the possibility to set the speed. Wonderful thing you provide us with the custom photo for the watchface but what is the extension of the file we could use? I tried to browse in my phone gallery and no photo is selectable. Thanks

**Comment by tibor-borsos-developments** [comment]
Hello!

You can upload watch face bin files, not image files.

**Comment by kime01** [comment]
How can we create bin watchface files?
